import type { Clash } from "./types";

// Dummy clashes referencing Building/ IFC files.
// IFC GUIDs below are placeholders — replace with real GUIDs from the actual IFC files
// once the clash/ engine produces report.bcf.
export const DUMMY_CLASHES: Clash[] = [
  {
    guid: "clash-001",
    id: "CLH-001",
    title: "HVAC duct vs STR beam",
    description: "Ventilation duct intersects structural beam at level 02, zone B3. The duct path needs to be rerouted or the beam opening needs to be coordinated.",
    status: "in_progress",
    priority: "urgent",
    ruleId: "HVAC×STR",
    ifcGuidA: "0ZmQ8$tq5EyhLGkXVe3OHd",
    ifcGuidB: "1aB2kR9xYpWmTqNjLs4VUw",
    fileA: "Building-Hvac.ifc",
    fileB: "Building-Structural.ifc",
    midpoint: [5.2, 3.1, 4.0],
    viewpoint: {
      cameraPosition: [5.2, 6.0, 12.0],
      cameraDirection: [0, -0.4, -0.9],
      cameraUpVector: [0, 1, 0],
      target: [5.2, 3.1, 4.0],
    },
    assignee: "michael.wk",
    labels: ["level-02", "zone-B3"],
    createdAt: "2026-03-26T09:00:00Z",
  },
  {
    guid: "clash-002",
    id: "CLH-002",
    title: "HVAC pipe vs ARCH wall",
    description: "Pipe clashes with interior partition wall at axis D/4. Coordination needed with architecture team.",
    status: "open",
    priority: "high",
    ruleId: "HVAC×ARCH",
    ifcGuidA: "2cD3lS0yZqXnUrOkMt5WVx",
    ifcGuidB: "3eE4mT1zArYoVsPjNu6XWy",
    fileA: "Building-Hvac.ifc",
    fileB: "Building-Architecture.ifc",
    midpoint: [-2.8, 2.4, 1.5],
    viewpoint: {
      cameraPosition: [-2.8, 5.0, 10.0],
      cameraDirection: [0, -0.35, -0.94],
      cameraUpVector: [0, 1, 0],
      target: [-2.8, 2.4, 1.5],
    },
    labels: ["level-01"],
    createdAt: "2026-03-26T09:05:00Z",
  },
  {
    guid: "clash-003",
    id: "CLH-003",
    title: "HVAC pipe vs STR slab",
    description: "Hot water pipe penetrates structural slab without sleeve coordination. Structural engineer review required.",
    status: "open",
    priority: "urgent",
    ruleId: "HVAC×STR",
    ifcGuidA: "4fF5nU2aBsZpWtQkOv7YXz",
    ifcGuidB: "5gG6oV3bCtAqXuRlPw8ZYa",
    fileA: "BIM_3W_Team2_MEP.ifc",
    fileB: "BIM_3W_Team2_STR.ifc",
    midpoint: [1.0, 0.05, 3.5],
    viewpoint: {
      cameraPosition: [1.0, 4.0, 10.0],
      cameraDirection: [0, -0.38, -0.93],
      cameraUpVector: [0, 1, 0],
      target: [1.0, 0.05, 3.5],
    },
    labels: ["slab", "level-01"],
    createdAt: "2026-03-26T09:10:00Z",
  },
  {
    guid: "clash-004",
    id: "CLH-004",
    title: "HVAC duct vs ARCH ceiling",
    description: "Supply air duct runs through finished ceiling space. Plenum height insufficient.",
    status: "in_review",
    priority: "medium",
    ruleId: "HVAC×ARCH",
    ifcGuidA: "6hH7pW4cDuBrYvSmQx9ZAb",
    ifcGuidB: "7iI8qX5dEvCsZwTnRyABc",
    fileA: "Building-Hvac.ifc",
    fileB: "Building-Architecture.ifc",
    midpoint: [8.5, 2.8, 6.2],
    viewpoint: {
      cameraPosition: [8.5, 5.5, 12.0],
      cameraDirection: [0, -0.32, -0.95],
      cameraUpVector: [0, 1, 0],
      target: [8.5, 2.8, 6.2],
    },
    assignee: "anna.b",
    labels: ["ceiling", "level-02"],
    createdAt: "2026-03-26T09:15:00Z",
  },
  {
    guid: "clash-005",
    id: "CLH-005",
    title: "HVAC pipe vs STR column",
    description: "HVAC pipe crosses structural column without clearance. Reroute one of the services.",
    status: "open",
    priority: "medium",
    ruleId: "HVAC×STR",
    ifcGuidA: "8jJ9rY6eFwDtAwUnSzBCd",
    ifcGuidB: "9kK0sZ7fGxEuBxVoTAcDe",
    fileA: "Building-Hvac.ifc",
    fileB: "Building-Structural.ifc",
    midpoint: [-5.0, 3.5, 5.8],
    viewpoint: {
      cameraPosition: [-5.0, 6.5, 13.0],
      cameraDirection: [0, -0.33, -0.94],
      cameraUpVector: [0, 1, 0],
      target: [-5.0, 3.5, 5.8],
    },
    labels: ["cable-tray", "level-02"],
    createdAt: "2026-03-26T09:20:00Z",
  },
  {
    guid: "clash-006",
    id: "CLH-006",
    title: "STR column vs ARCH door frame",
    description: "Structural column encroaches on door frame opening at axis B/2. Requires architectural revision.",
    status: "in_progress",
    priority: "high",
    ruleId: "STR×ARCH",
    ifcGuidA: "AkL1tA8gHyFvCyWpUbDeF",
    ifcGuidB: "BlM2uB9hIzGwDzXqVcEfG",
    fileA: "Building-Structural.ifc",
    fileB: "Building-Architecture.ifc",
    midpoint: [3.3, 1.2, 2.1],
    viewpoint: {
      cameraPosition: [3.3, 4.0, 9.0],
      cameraDirection: [0, -0.37, -0.93],
      cameraUpVector: [0, 1, 0],
      target: [3.3, 1.2, 2.1],
    },
    assignee: "michael.wk",
    labels: ["door", "level-01"],
    createdAt: "2026-03-26T09:25:00Z",
  },
  {
    guid: "clash-007",
    id: "CLH-007",
    title: "HVAC duct vs STR foundation",
    description: "Underground duct intersects structural foundation below basement slab. Elevation adjustment needed.",
    status: "open",
    priority: "low",
    ruleId: "HVAC×STR",
    ifcGuidA: "CmN3vC0iJaHxEaYrWdFgH",
    ifcGuidB: "DnO4wD1jKbIyFbZsXeGhI",
    fileA: "Building-Hvac.ifc",
    fileB: "Building-Structural.ifc",
    midpoint: [0.0, -0.5, 0.8],
    viewpoint: {
      cameraPosition: [0.0, 3.0, 8.0],
      cameraDirection: [0, -0.38, -0.93],
      cameraUpVector: [0, 1, 0],
      target: [0.0, -0.5, 0.8],
    },
    labels: ["basement", "underground"],
    createdAt: "2026-03-26T09:30:00Z",
  },
  {
    guid: "clash-008",
    id: "CLH-008",
    title: "ARCH wall vs STR footing",
    description: "Architectural wall conflicts with structural footing layout.",
    status: "resolved",
    priority: "medium",
    ruleId: "ARCH×STR",
    ifcGuidA: "EoP5xE2kLcJzGcAsYfHiJ",
    ifcGuidB: "FpQ6yF3lMdKaHdBtZgIjK",
    fileA: "Building-Architecture.ifc",
    fileB: "Building-Structural.ifc",
    midpoint: [-8.0, -1.0, -0.5],
    viewpoint: {
      cameraPosition: [-8.0, 2.0, 7.0],
      cameraDirection: [0, -0.35, -0.94],
      cameraUpVector: [0, 1, 0],
      target: [-8.0, -1.0, -0.5],
    },
    labels: ["footing", "foundation"],
    createdAt: "2026-03-25T14:00:00Z",
  },
];

export const STATUS_ORDER: Clash["status"][] = [
  "in_progress",
  "in_review",
  "open",
  "resolved",
  "closed",
];
