name: Rust CI

on:
  push:
    branches: [ "main", "stage" ]
  pull_request:
    branches: [ "main", "stage" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install Rust
        run: rustup update stable && rustup component add rustfmt
        working-directory: ./clash
      - name: Check formatting
        working-directory: ./clash
        run: cargo fmt --check

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Build
        working-directory: ./clash
        run: cargo build --verbose

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Run tests
        working-directory: ./clash
        run: cargo test --verbose
